### ISSUE TITLE
Impossible to scroll on Mac (latest el Captain) with trackpad in Chrome Version 53.0.2785.116 (64-bit)

### ISSUE THREAD

**Issue by aosmichenko** [Viewdesic/viewScroller.js#1]
Tested on demo page

**Comment by Viewdesic** [comment]
Thanks for testing! I will fix it soon.

**Comment by nr1q** [comment]
Hello, I also had problem when scrolling on the same environment. In Firefox almost works, but the mouse scroll jumps to the top or to the bottom, couldn't get into the middle sections, only with the arrow keys.

**Comment by Viewdesic** [comment]
Hi, thanks for info. I will check it.

**Comment by Viewdesic** [comment]
Fixed. Look at the new release 2.0.3. Tested on BrowserStack on MAC (el Captain) platform.

**Comment by aosmichenko** [comment]
Did you updated demo with this new fix? because it is still not scrollable here it is jumping like a crazy frog. If you need video I can do screencapture for you..

**Comment by Viewdesic** [comment]
You are right, I forgot to update main mousewheel function. Now, should be OK :)
